### ISSUE TITLE
keystone v3

### ISSUE THREAD

**Issue by dtamez** [Memset/sftpcloudfs#14]
Are there any plans to support keystone's v3 authentication?  If not would you be open to a patch?

**Comment by stenstad** [comment]
Hi, swiftclient now supports Identity v3. :-)

**Comment by reidrac** [comment]
Yes, it in our TODO. Coming! :)

**Comment by skydiablo** [comment]
coming soon?

**Comment by reidrac** [comment]
Not working on it at the moment, but it should be trivial.

I see than V2 being removed from keystone makes this high priority, but I currently don't have a Keystone v3 service available for testing, so it is... complicated.

**Comment by reidrac** [comment]
Done in #26 .
