### ISSUE TITLE
Performance improvement, packet size 16Kbits, chunk 

### ISSUE THREAD

**Issue by axelJacquet** [Memset/sftpcloudfs#35]
Hello,

Currently I use this project to send data to my Swift infrastructure. We encounter some performance issue when reading/writing big files (> dozen MB)  from/to swift. We did serveral tests, one of those for instance using rclone shows that when uploading a big file (2GB) into swift using rclone swift backend type we reach a speed of 200MB/s (both ways : upload/download). Then, using rclone sftp backend pointing to sftpcloudfs (running locally), we only reach 6MB/s (local to swift) and 3MB/s (Swift to local).
It looks like there's a huge overhead reading remote file by small chunks. Do you think there's a way to improve this, if so, could finger point where to look at in the code ? :-)

**Comment by reidrac** [comment]
This service uses an SSH implementation in Python (Paramiko). The performance I don't think it'll be close to what you get in a compiled language.

I don't know if this can be improved at HTTPS level (communication between sfpcloufs and swift), but if that's the case, the code is in ftp-cloudfs that this project uses as base for the filesystem abstraction.

If the performance is on the Paramiko side, then I have no idea. If you need performance, perhaps using rclone will work better for you.

**Comment by ncw** [comment]
I'll just note that if you are already familiar with rclone, you can use `rclone serve sftp swiftremote:` which does what `sftpcloudfs` does pretty much. You can use the auth proxy (see the docs) to map incoming user/password/key to remote auth on the swift cluster.

**Comment by axelJacquet** [comment]
Hello, thanks a lot for your fast reply and clarifications, i will test rclone with sftp serve.

Best regards
